export default {
    VIEW_REFRESH: 'VIEW_REFRESH',
    SAVE_VALUE:'SAVE_VALUE',
    CLEAR_VIEW:'CLEAR_VIEW',
    CLEAR_VALUE_TO_NEXT_ACTION:'CLEAR_VALUE_TO_NEXT_ACTION',
    SET_OPERATION:'SET_OPERATION',
    CLEAR_OPERATION:'CLEAR_OPERATION',
    ENTER_DECIMAIS_DIGITS:'ENTER_DECIMAIS_DIGITS'
}